// Visual corpus generated by the public Core preview. This route renders an
// acquired snap; gesture timing is exercised separately through AlbumCanvas.
import { Application, Container } from "pixi.js";
import corpus from "../../tests/fixtures/frame-snap-cases.json";
import type { ComposedSheet, DisplayUnit, FrameGeometryEdit, FrameGeometryPreview } from "../domain/project";
import type { AlbumCanvasProps } from "../components/albumCanvasContract";
import { AlbumCanvasScene } from "../components/albumCanvasScene";
import { createContinuousCanvasLayout } from "../components/canvasGeometry";
import { createFrameSnapGuideRenderNode } from "../components/frameSnapGuideRenderNode";
import { mediaPanelPreviewFixture } from "./mediaPanelPreviewFixtures";
import "../components/AlbumCanvas.css";
import "../components/pixiRuntime";

const params = new URLSearchParams(window.location.search);
const item = corpus.cases.find((entry) => entry.name === (params.get("case") ?? "width")) as unknown as {
  name: string; sheet: ComposedSheet; edit: FrameGeometryEdit; preview: FrameGeometryPreview;
  technicalGuides: { bleedUm: number; safetyUm: number };
};
if (!item) throw new Error("Unknown Core snap case");
const sheet = structuredClone(item.sheet);
for (const frame of item.preview.frames) {
  sheet.frames[sheet.frames.findIndex((original) => original.frameId === frame.frameId)] = frame;
}
const app = new Application();
const height = params.get("scale") === "small" ? 360 : 680;
await app.init({ width: window.innerWidth, height, background: "#ddd", preference: "webgl", resolution: window.devicePixelRatio, autoDensity: true });
app.canvas.className = "pixi-canvas";
document.body.appendChild(app.canvas);
let textureReady!: () => void;
let textureFailed!: (error: Error) => void;
const texture = new Promise<void>((resolve, reject) => { textureReady = resolve; textureFailed = reject; });
const scene = new AlbumCanvasScene(app, () => textureFailed(new Error("The preview image failed to load")), textureReady);
const composition = { frameBorder: { kind: "none" as const }, sheets: [sheet] };
const unit = (params.get("unit") ?? "mm") as DisplayUnit;
let scale = 1;
const noop = () => undefined;
const input: AlbumCanvasProps = {
  projectId: "snap-evidence", composition,
  mediaPreviewUrls: { "00000000-0000-4000-8000-000000000001": mediaPanelPreviewFixture.mediaPreviews["test-media-001"]!.url },
  mode: { kind: "sheet-editing", sheetId: sheet.sheetId },
  sheetBarMetadata: [{ sheetId: sheet.sheetId, pageNumbers: sheet.activeSides === "both" ? [1, 2] : [1], layoutLocked: false }],
  continuousCanvasLayout: createContinuousCanvasLayout(composition.sheets),
  selectedFrameIds: item.edit.frames.map((frame) => frame.frameId), focusedSheetId: sheet.sheetId, centeredSheetId: sheet.sheetId,
  viewport: { offsetX: 0 }, displayUnit: unit, frameGapUm: 5_000,
  technicalGuides: item.technicalGuides,
  onCanvasMetricsChange: (metrics) => { scale = metrics.scale; },
  onSelectFrame: noop, onEditSheet: noop, onFocusSheet: noop, onCenteredSheetChange: noop,
  onViewportChange: noop, onTransformPreview: noop, onTransformCommit: async () => true,
  frameGeometry: { disabled: false, dragThreshold: { x: 5, y: 5 },
    preview: async () => item.preview, commit: async () => item.preview.frames, onError: (message) => { throw new Error(message); } },
};
scene.update(input, height);
await texture;
function find(label: string, parent: Container = app.stage): Container | undefined {
  if (parent.label === label) return parent;
  for (const child of parent.children) { const found = find(label, child); if (found) return found; }
}
// Attach the production guide node at the production active-surface origin.
const target = find("frame-snap-guides");
if (!target) throw new Error("The editing scene did not create a snap layer");
const guides = createFrameSnapGuideRenderNode(sheet.widthUm, sheet.heightUm);
target.visible = true;
target.addChild(guides.container);
guides.update(item.preview.snap.guides, scale, unit);
app.render();
document.body.dataset.snapCase = item.name;
document.body.dataset.snapScale = String(scale);
