import type { EditorProjection, ProjectMutationOutcome } from "../domain/project";
import corpus from "../../tests/fixtures/sheet-duplication-cases.json";

// Persisted compositions and the command outcome are generated by the public Core.
export const sheetDuplicationCorpus = corpus as unknown as {
  before: EditorProjection;
  after: EditorProjection;
  reopened: EditorProjection;
  edited: EditorProjection;
  single: EditorProjection;
  outcome: ProjectMutationOutcome;
};
