pub(crate) const HOST_LEASE_ENDPOINT_ENV: &str = "MYALBUNS_DEV_HOST_LEASE_ENDPOINT";
pub(crate) const HOST_LEASE_AUTHORITY_ENV: &str = "MYALBUNS_DEV_HOST_LEASE_AUTHORITY";

pub(crate) const AUTHORIZE_HOST_LEASE_REQUEST: &str = "AUTHORIZE";
pub(crate) const REGISTER_HOST_LEASE_REQUEST: &str = "REGISTER";
pub(crate) const HOST_LEASE_AUTHORIZED_RESPONSE: &str = "AUTHORIZED\n";
pub(crate) const HOST_LEASE_REGISTERED_RESPONSE: &str = "REGISTERED\n";
